name: Game4Free-Renew

permissions:
  actions: write
  contents: read

on:
  schedule:
    - cron: '5 */1 * * *'
  workflow_dispatch:
    inputs:
      round:
        description: "当前轮数"
        required: false
        default: "1"

jobs:
  renew:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 📥 下载私库脚本
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/ActionNode-Start-Private
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private
    
      - name: 🔍 查看私库内容
        run: |
          echo "当前目录:"
          pwd

          echo "private目录:"
          ls -lah private

          echo "所有文件:"
          find private -type f

      - name: 🛡️ 启动 GOST 代理
        env:
          ALL_PROXIES: ${{ secrets.GOST_PROXY }}
          CURRENT_ROUND: ${{ github.event.inputs.round }}
        run: |
          ROUND=${CURRENT_ROUND:-1}

          if [ $((ROUND % 2)) -eq 1 ]; then
             PROXY=$(echo "$ALL_PROXIES" | sed -n '1p')
          else
             PROXY=$(echo "$ALL_PROXIES" | sed -n '2p')
          fi

          echo "当前轮数: $ROUND"
          echo "使用代理: $PROXY"

          VERSION=$(curl -s https://api.github.com/repos/ginuerzh/gost/releases/latest \
            | grep '"tag_name"' \
            | cut -d'"' -f4 \
            | tr -d 'v')

          wget -q "https://github.com/ginuerzh/gost/releases/download/v${VERSION}/gost_${VERSION}_linux_amd64.tar.gz"

          tar -xzf "gost_${VERSION}_linux_amd64.tar.gz"

          chmod +x gost

          nohup ./gost -L http://:8080 -F "$PROXY" > gost.log 2>&1 &

          sleep 5

          echo "✅ GOST 已启动"

      - name: 🛠️ 安装系统依赖
        run: |
          sudo apt-get update -q
          sudo apt-get install -y google-chrome-stable xvfb xdotool python3-tk python3-dev
          

      - name: 🐍 安装 Python 依赖
        run: |
          pip install -U pip
          pip install seleniumbase

      - name: 🔧 安装 ChromeDriver
        run: seleniumbase install chromedriver

      - name: 🚀 运行续期脚本
        env:
          PYTHONIOENCODING: utf-8
          TG_BOT: ${{ secrets.TG_BOT }}
          GAME4FREE_ACCOUNT: ${{ secrets.GAME4FREE_ACCOUNT }}
          GOST_PROXY: ${{ secrets.GOST_PROXY }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            python private/game4free_renew.py

      - name: 📸 上传截图
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots-${{ github.run_number }}
          path: "*.png"
          if-no-files-found: ignore
          
      - name: 查看 workflow
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
       run: |
         curl \
           -H "Authorization: Bearer $GH_TOKEN" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows
           
      - name: 🔁 触发下一轮
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
          CURRENT_ROUND: ${{ github.event.inputs.round }}
        run: |
         set -x

         ROUND=${CURRENT_ROUND:-1}
         NEXT=$((ROUND + 1))

         echo "CURRENT=$ROUND"
         echo "NEXT=$NEXT"

         if [ "$NEXT" -le 8 ]; then

           curl -i -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/game4free_renew.yml/dispatches
            -d "{\"ref\":\"${{ github.ref_name }}\",\"inputs\":{\"round\":\"$NEXT\"}}"

       else
         echo "DONE"
       fi
